name: CD pipeline
on:
  workflow_run:
    workflows: [build-test-ship]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: kubectl set image deployments/weather-ml-app-deployment weather-ml-app=harryhavana/weather-ml-app:latest && ./multiple_users.sh
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
